### ISSUE TITLE
Unable to load skills from Kitlaan - Error loading kitlaan data: Error: Error: [object Object]

### ISSUE THREAD

**Issue by uberpewpew** [fat4eyes-mwo/mwo-simulator#23]
Can't load Kilaan skills using perma link.

Error message:
Unable to load skills from Kitlaan - Error loading kitlaan data: Error: Error: [object Object]

**Comment by fat4eyes-mwo** [comment]
Yeah it's getting 404s when trying to load kitlaan's skill data. I'll have a look at it this weekend. Thanks for the report.

**Comment by fat4eyes-mwo** [comment]
It seems that kitlaan's skill tree planer is having issues getting state from jsonbin as well. I've added a comment on his gitlab project and am waiting for a reply.

**Comment by fat4eyes-mwo** [comment]
Should be mostly fixed by 
https://github.com/fat4eyes-mwo/mwo-simulator/commit/ab8e2209d7dad4a67f044891f72ac4f3d6be69a1
https://github.com/fat4eyes-mwo/mwo-simulator/commit/3775a7c484ec08a821e8e7b84e37b72a1f3e267b
https://github.com/fat4eyes-mwo/mwo-simulator/commit/968c9a21d6b9d8220daa440c0a9ff5417306e3a2

and the site at http://www.4eye-labs.net/mwo-simulator/ have these changes in.

Kitlaan permlinks created before Jan 2018 should work, but those created after do not. This will probably be fixed once kitlaan finds a solution to the jsonbin issue. Will watch to see how he fixes it.

Will need to wait for kitlaan's final solution to jsonbin issue before closing.

**Comment by fat4eyes-mwo** [comment]
Should be fixed. Removed kitlaan load skill notice in https://github.com/fat4eyes-mwo/mwo-simulator/commit/125011f0b17c52c629e4d13ca1e85719e1168a9e

Closing.
